export const FETCH_ALL_ALBUMS = 'FETCH_ALL_ALBUMS';
export const FETCH_SINGLE_ALBUM = 'FETCH_SINGLE_ALBUM';
export const FAVOURITE_ALBUM = 'FAVOURITE_ALBUM';
export const UNFAVOURITE_ALBUM ='UNFAVOURITE_ALBUM';

